"""followers

Revision ID: 1824376b02cd
Revises: 95d1b0a7bc3b
Create Date: 2019-11-12 22:08:35.232752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1824376b02cd'
down_revision = '95d1b0a7bc3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
