"""user points test 2

Revision ID: 057e110bc6fc
Revises: cbd2369b5608
Create Date: 2019-11-19 21:22:03.001204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057e110bc6fc'
down_revision = 'cbd2369b5608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user_category_points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
