"""xp_to_next_level_constant

Revision ID: 61c37cd7f708
Revises: 
Create Date: 2019-12-18 12:44:59.286075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c37cd7f708'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_category_timestamp'), 'category', ['timestamp'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('level_up_xp_modifier', sa.Integer(), nullable=True),
    sa.Column('xp_to_next_level', sa.Integer(), nullable=True),
    sa.Column('xp_to_next_level_constant', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_level'), 'user', ['level'], unique=False)
    op.create_index(op.f('ix_user_level_up_xp_modifier'), 'user', ['level_up_xp_modifier'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_index(op.f('ix_user_xp'), 'user', ['xp'], unique=False)
    op.create_index(op.f('ix_user_xp_to_next_level'), 'user', ['xp_to_next_level'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.DateTime(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_completed'), 'session', ['completed'], unique=False)
    op.create_index(op.f('ix_session_created'), 'session', ['created'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_timestamp'), 'task', ['timestamp'], unique=False)
    op.create_index(op.f('ix_task_xp'), 'task', ['xp'], unique=False)
    op.create_table('user_category',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user_category_level', sa.Integer(), nullable=True),
    sa.Column('user_category_xp', sa.Integer(), nullable=True),
    sa.Column('level_up_xp_modifier', sa.Integer(), nullable=True),
    sa.Column('xp_to_next_level', sa.Integer(), nullable=True),
    sa.Column('xp_to_next_level_constant', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'category_id')
    )
    op.create_index(op.f('ix_user_category_user_category_level'), 'user_category', ['user_category_level'], unique=False)
    op.create_index(op.f('ix_user_category_user_category_xp'), 'user_category', ['user_category_xp'], unique=False)
    op.create_table('session_tasks_atable',
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_tasks_atable')
    op.drop_index(op.f('ix_user_category_user_category_xp'), table_name='user_category')
    op.drop_index(op.f('ix_user_category_user_category_level'), table_name='user_category')
    op.drop_table('user_category')
    op.drop_index(op.f('ix_task_xp'), table_name='task')
    op.drop_index(op.f('ix_task_timestamp'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_session_created'), table_name='session')
    op.drop_index(op.f('ix_session_completed'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_user_xp_to_next_level'), table_name='user')
    op.drop_index(op.f('ix_user_xp'), table_name='user')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_level_up_xp_modifier'), table_name='user')
    op.drop_index(op.f('ix_user_level'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_category_timestamp'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
