"""empty message

Revision ID: 8636a5166032
Revises: bb03e420fa9f
Create Date: 2019-11-24 17:42:52.677385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8636a5166032'
down_revision = 'bb03e420fa9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('level_up_xp_modifier', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('xp_to_next_level', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_level'), 'user', ['level'], unique=False)
    op.create_index(op.f('ix_user_level_up_xp_modifier'), 'user', ['level_up_xp_modifier'], unique=False)
    op.create_index(op.f('ix_user_xp_to_next_level'), 'user', ['xp_to_next_level'], unique=False)
    op.add_column('user_category_xp', sa.Column('user_category_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_category_xp', 'user_category_level')
    op.drop_index(op.f('ix_user_xp_to_next_level'), table_name='user')
    op.drop_index(op.f('ix_user_level_up_xp_modifier'), table_name='user')
    op.drop_index(op.f('ix_user_level'), table_name='user')
    op.drop_column('user', 'xp_to_next_level')
    op.drop_column('user', 'level_up_xp_modifier')
    op.drop_column('user', 'level')
    # ### end Alembic commands ###
